export const SPAWN_CONFIG = {
  obstacleStartDistance: 92,
  flowerStartDistance: 34,
  decorStartDistance: 2,
  sideDecorSpacing: 11.0,
  sideDecorJitter: 0.45,
  sideDecorNearCullDistance: -5.5,
  sideDecorHeroMaxGap: 16,
  scatterSpacing: 3.2,
  scatterPatchSpacing: 9.2,
  scatterPatchBands: 2,
  scatterPatchBandSpacing: 1.35,
  scatterClusterLaneRadius: 0.22,
  scatterPerBand: 6,
  scatterLaneRange: [1.34, 1.90],
  scatterMaxDistance: 120,
  scatterMeadowFraction: 0.60,
  lifePickupMinDistance: 940,
  lifePickupMaxDistance: 1480,
  powerUpMinDistance: 780,
  powerUpMaxDistance: 1220,
  rareOrchidMinDistance: 1800,
  rareOrchidMaxDistance: 3600,
  rareOrchidBaseScore: 25,
  density: {
    centerTrailYieldsToFigures: true,
    orchidFillerYieldsToFigures: true,
    figureWindow: 4,
    orchidTickMaxIntensity: 0.35,
  },
};
